import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { impliedVol } from "../../pricing/implied-vol";
import type { OptionType, SviSliceInput } from "../../types";
import { worstCrossing } from "../calendar";
import { fitSurface } from "../index";
import { filterQuotes, type RawQuote } from "../quotes";
import { butterflyViolations, sviImpliedVol } from "../svi";

// fit the surface against the real IBM chain rather than synthetic quotes. a
// synthetic slice is generated by the same formula the fit assumes, so it can
// only ever confirm the optimiser. real chains carry wide spreads, stale marks
// and quotes that cross - the cases that decide whether the constraints hold.

interface VendorRow {
  expiration: string;
  strike: string;
  type: string;
  mark: string;
  bid: string;
  ask: string;
  volume: string;
  open_interest: string;
  date: string;
  implied_volatility: string;
}

const FIXTURE = join(
  import.meta.dirname,
  "..",
  "..",
  "..",
  "..",
  "fixtures",
  "ibm-chain-2026-07-20.json",
);
const rows: VendorRow[] = JSON.parse(readFileSync(FIXTURE, "utf8")).data;

const AS_OF = new Date(`${rows[0]!.date}T00:00:00Z`).getTime();
const YEAR_MS = 365 * 24 * 3600 * 1000;
const RATE = 0.04;
const DIV_YIELD = 0.01;
// established in vendor-fixture.test.ts by put-call parity on the front expiry
const SPOT = 212.98;

const yearsTo = (expiration: string): number =>
  (new Date(`${expiration}T00:00:00Z`).getTime() - AS_OF) / YEAR_MS;

/** forward under continuous carry, which is what log-moneyness is measured against */
const forwardFor = (t: number): number => SPOT * Math.exp((RATE - DIV_YIELD) * t);

/**
 * build slice inputs from the chain: solve our own IV per contract, keep the
 * out-of-the-money side of each strike (the liquid one), then run the shared
 * quote filter so the test and backend ingestion select quotes identically.
 */
const buildInputs = (): SviSliceInput[] => {
  const byExpiry = new Map<string, RawQuote[]>();

  for (const row of rows) {
    const t = yearsTo(row.expiration);
    const strike = Number.parseFloat(row.strike);
    const mark = Number.parseFloat(row.mark);
    if (!(t > 0) || !(mark > 0) || !(strike > 0)) continue;

    const forward = forwardFor(t);
    const type = row.type as OptionType;
    // keep the OTM leg: calls above the forward, puts below. the ITM leg carries
    // most of its value as intrinsic, so its IV is dominated by spread noise
    const otm = type === "call" ? strike >= forward : strike < forward;
    if (!otm) continue;

    const solved = impliedVol({
      type,
      S: SPOT,
      K: strike,
      r: RATE,
      T: t,
      q: DIV_YIELD,
      price: mark,
    });

    const bucket = byExpiry.get(row.expiration) ?? [];
    bucket.push({
      strike,
      mark,
      bid: Number.parseFloat(row.bid),
      ask: Number.parseFloat(row.ask),
      volume: Number.parseFloat(row.volume),
      openInterest: Number.parseFloat(row.open_interest),
      iv: solved.iv,
    });
    byExpiry.set(row.expiration, bucket);
  }

  return [...byExpiry.entries()]
    .map(([expiration, raw]) => {
      const t = yearsTo(expiration);
      const forward = forwardFor(t);
      return { expiration, t, forward, quotes: filterQuotes(raw, forward, t).quotes };
    })
    .sort((a, b) => a.t - b.t);
};

const inputs = buildInputs();
const surface = fitSurface(inputs);

describe("surface fit against the real IBM chain", () => {
  it("builds slice inputs across the term structure", () => {
    expect(inputs.length).toBeGreaterThan(10);
    for (const input of inputs) {
      expect(input.t).toBeGreaterThan(0);
      expect(input.forward).toBeGreaterThan(0);
    }
  });

  it("fits most expiries in the chain", () => {
    expect(surface.slices.length).toBeGreaterThan(10);
    // anything dropped was dropped for thin quotes, not silently mangled
    for (const expiration of surface.skippedExpirations) {
      const input = inputs.find((i) => i.expiration === expiration);
      expect(input?.quotes.length ?? 0).toBeLessThan(5);
    }
  });

  it("produces a butterfly arb-free slice for every fitted expiry", () => {
    for (const slice of surface.slices) {
      expect(butterflyViolations(slice.params)).toEqual([]);
      expect(slice.butterflyArbFree).toBe(true);
    }
  });

  it("produces a calendar arb-free term structure", () => {
    expect(surface.calendarArbFree).toBe(true);
    for (let i = 1; i < surface.slices.length; i++) {
      const earlier = surface.slices[i - 1];
      const later = surface.slices[i];
      if (earlier === undefined || later === undefined) continue;
      expect(worstCrossing(earlier, later)).toBeNull();
    }
  });

  it("lands ATM vol inside the range its own quotes span", () => {
    // the strongest available check that the fit sits on the data rather than
    // near it: the fitted level at the money must fall within the observed
    // vols for that expiry, not merely inside some wide plausible band
    for (const slice of surface.slices) {
      const input = inputs.find((i) => i.expiration === slice.expiration);
      if (input === undefined || input.quotes.length === 0) continue;

      const observed = input.quotes.map((q) => Math.sqrt(q.w / slice.t));
      const atmVol = sviImpliedVol(slice.params, 0, slice.t);

      expect(atmVol).not.toBeNull();
      expect(atmVol as number).toBeGreaterThanOrEqual(Math.min(...observed) - 1e-9);
      expect(atmVol as number).toBeLessThanOrEqual(Math.max(...observed) + 1e-9);
    }
  });

  it("reproduces each slice's own quotes closely", () => {
    for (const slice of surface.slices) {
      const input = inputs.find((i) => i.expiration === slice.expiration);
      if (input === undefined) continue;

      const errors = input.quotes
        .map((q) => {
          const fitted = sviImpliedVol(slice.params, q.k, slice.t);
          if (fitted === null) return null;
          const observed = Math.sqrt(q.w / slice.t);
          return Math.abs(fitted - observed);
        })
        .filter((e) => e !== null)
        .sort((a, b) => a - b);

      // the fit is a 5-parameter curve through a noisy cloud, so judge it on the
      // median rather than the worst wing quote. measured across this chain the
      // median lands between 0.0024 and 0.0086 of vol, so 0.02 is a real bound
      // rather than one loose enough to pass regardless
      const median = errors[Math.floor(errors.length / 2)] ?? 0;
      expect(median).toBeLessThan(0.02);
    }
  });

  it("reproduces the equity down-skew, measured as the fitted slope at the money", () => {
    // puts below the forward trade at higher vol than calls above it. the test
    // is the ATM slope of the fitted curve, NOT the sign of rho: rho describes
    // the wings relative to the vertex at m, so a slice whose vertex sits right
    // of the money is legitimately rho > 0 while still sloping down at k = 0.
    // measured on this chain, the observed slope runs -0.006 at the front to
    // -0.054 at 2.4 years, and the fit tracks it.
    const h = 0.1;
    const downSkewed = surface.slices.filter((slice) => {
      const down = sviImpliedVol(slice.params, -h, slice.t);
      const up = sviImpliedVol(slice.params, h, slice.t);
      if (down === null || up === null) return false;
      return up < down;
    });

    // the two shortest expiries genuinely skew the other way on this chain -
    // a four-day smile is dominated by an event bid, not by crash protection
    expect(downSkewed.length).toBeGreaterThanOrEqual(surface.slices.length - 3);
  });

  it("steepens the down-skew as maturity grows", () => {
    // the term structure of skew: longer expiries carry more crash premium, so
    // the ATM slope gets more negative further out
    const slopeAt = (index: number): number => {
      const slice = surface.slices[index];
      if (slice === undefined) return 0;
      const down = sviImpliedVol(slice.params, -0.1, slice.t) ?? 0;
      const up = sviImpliedVol(slice.params, 0.1, slice.t) ?? 0;
      return up - down;
    };

    const front = slopeAt(Math.floor(surface.slices.length / 3));
    const back = slopeAt(surface.slices.length - 1);
    expect(back).toBeLessThan(front);
  });

  it("renders a mesh that is finite where quoted and null where not", () => {
    const { grid } = surface;
    expect(grid.expiries.length).toBe(surface.slices.length);
    expect(grid.iv.length).toBe(surface.slices.length);

    let covered = 0;
    for (let row = 0; row < grid.iv.length; row++) {
      const slice = surface.slices[row];
      const values = grid.iv[row];
      if (slice === undefined || values === undefined) continue;
      expect(values.length).toBe(grid.moneyness.length);

      for (let col = 0; col < values.length; col++) {
        const k = grid.moneyness[col] as number;
        const value = values[col];
        const supported = k >= slice.kMin && k <= slice.kMax;

        if (!supported) {
          // outside the quoted range the mesh must stay empty rather than
          // render an extrapolated wing as if it were observed
          expect(value).toBeNull();
          continue;
        }
        expect(value).not.toBeNull();
        expect(Number.isFinite(value as number)).toBe(true);
        expect(value as number).toBeGreaterThan(0);
        covered++;
      }
    }

    // the surface has to be mostly real, not mostly holes
    expect(covered).toBeGreaterThan(grid.iv.length * grid.moneyness.length * 0.5);

    for (const row of grid.strikes) {
      for (const strike of row) {
        expect(Number.isFinite(strike)).toBe(true);
        expect(strike).toBeGreaterThan(0);
      }
    }
  });

  it("keeps total variance non-decreasing across the rendered mesh", () => {
    const { grid } = surface;
    let compared = 0;

    for (let col = 0; col < grid.moneyness.length; col++) {
      for (let row = 1; row < grid.iv.length; row++) {
        const earlierIv = grid.iv[row - 1]?.[col];
        const laterIv = grid.iv[row]?.[col];
        const earlierT = grid.years[row - 1];
        const laterT = grid.years[row];
        // nulls are nodes outside a slice's quoted range, so there is nothing
        // to compare there
        if (earlierIv == null || laterIv == null || earlierT == null || laterT == null) continue;

        expect(laterIv * laterIv * laterT).toBeGreaterThanOrEqual(
          earlierIv * earlierIv * earlierT - 1e-9,
        );
        compared++;
      }
    }

    // guard against the assertion silently passing because everything was null
    expect(compared).toBeGreaterThan(100);
  });
});
