#!/usr/bin/env bun
// copies engine/src into each service so backend and frontend stay fully
// self-contained - neither ever imports across a service boundary.
//
//   bun run sync-engine           copy, overwriting each target
//   bun run sync-engine --check   verify copies are in sync, exit 1 if not
//
// the sync is deliberately manual. --check exists so a stale or hand-edited
// copy fails a build instead of silently pricing differently to its source.

import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const SOURCE = join(ROOT, "engine", "src");
const TARGETS = [join(ROOT, "backend", "src", "engine"), join(ROOT, "frontend", "src", "engine")];

const BANNER_MARK = "generated by scripts/sync-engine.ts";

const banner = (hash: string): string =>
  `// ${BANNER_MARK} - DO NOT EDIT\n` +
  `// canonical source: engine/src. edit there, then run: bun run sync-engine\n` +
  `// source-sha256: ${hash}\n\n`;

const sha256 = (text: string): string =>
  createHash("sha256").update(text).digest("hex").slice(0, 16);

// tests stay in the canonical engine package only - services ship the math, not its test suite
const isTestPath = (path: string): boolean => path.includes("_tests") || path.endsWith(".test.ts");

const collect = async (dir: string, base = dir): Promise<string[]> => {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await collect(full, base)));
      continue;
    }
    if (!entry.name.endsWith(".ts")) continue;
    const rel = relative(base, full);
    if (isTestPath(rel)) continue;
    files.push(rel);
  }

  return files.sort();
};

interface SyncFile {
  rel: string;
  contents: string;
  hash: string;
}

const readSource = async (): Promise<SyncFile[]> => {
  const rels = await collect(SOURCE);
  return Promise.all(
    rels.map(async (rel) => {
      const contents = await readFile(join(SOURCE, rel), "utf8");
      return { rel, contents, hash: sha256(contents) };
    }),
  );
};

const check = async (files: SyncFile[]): Promise<boolean> => {
  let ok = true;

  for (const target of TARGETS) {
    if (!existsSync(target)) {
      console.error(`  stale: ${relative(ROOT, target)} does not exist`);
      ok = false;
      continue;
    }

    const present = new Set(await collect(target));

    for (const file of files) {
      const dest = join(target, file.rel);
      if (!existsSync(dest)) {
        console.error(`  missing: ${relative(ROOT, dest)}`);
        ok = false;
        continue;
      }
      present.delete(file.rel);

      // compare the full expected file, not just the recorded stamp - a hand
      // edit below the banner leaves the stamp intact and must still be caught
      const actual = await readFile(dest, "utf8");
      if (actual !== banner(file.hash) + file.contents) {
        console.error(`  drifted: ${relative(ROOT, dest)}`);
        ok = false;
      }
    }

    for (const orphan of present) {
      console.error(`  orphaned: ${relative(ROOT, join(target, orphan))}`);
      ok = false;
    }
  }

  return ok;
};

const write = async (files: SyncFile[]): Promise<void> => {
  for (const target of TARGETS) {
    // clear first so a file deleted from the engine cannot linger in a copy
    await rm(target, { recursive: true, force: true });
    await mkdir(target, { recursive: true });

    for (const file of files) {
      const dest = join(target, file.rel);
      await mkdir(dirname(dest), { recursive: true });
      await writeFile(dest, banner(file.hash) + file.contents, "utf8");
    }

    console.log(`  ${relative(ROOT, target)} <- ${files.length} files`);
  }
};

const main = async (): Promise<void> => {
  if (!existsSync(SOURCE)) {
    console.error(`engine source not found at ${SOURCE}`);
    process.exit(1);
  }

  const files = await readSource();
  const checkOnly = process.argv.includes("--check");

  if (checkOnly) {
    console.log("checking engine copies");
    const ok = await check(files);
    if (!ok) {
      console.error("\nengine copies are out of sync. run: bun run sync-engine");
      process.exit(1);
    }
    console.log(`  in sync (${files.length} files)`);
    return;
  }

  console.log("syncing engine");
  await write(files);
};

await main();
